[metadata]
addr = 0x11da
size = 0x64
last_change = 2023-12-10T07:10:08.038833Z

[header]
last_change = 2023-12-10T07:10:08.038833Z
name = "append_list"
addr = 0x11da
type = "node *"

[header.args.0]
offset = 0x0
name = "a1"
type = "node *"
size = 0x8

[header.args.1]
offset = 0x1
name = "key"
type = "char"
size = 0x1

[header.args.2]
offset = 0x2
name = "file_value"
type = "char"
size = 0x1
