[0x11b8]
last_change = 2023-12-10T06:55:32.834339Z
addr = 0x11b8
func_addr = 0x11b5
comment = "if head is null\n"
decompiled = true

[0x11e3]
last_change = 2023-12-10T07:04:11.202571Z
addr = 0x11e3
func_addr = 0x11da
comment = "if a1 is not the only node in the list\n"
decompiled = true

[0x120d]
last_change = 2023-12-10T07:03:09.307881Z
addr = 0x120d
func_addr = 0x11da
comment = "set new_node's key\n"
decompiled = true

[0x1214]
last_change = 2023-12-10T07:10:23.952562Z
addr = 0x1214
func_addr = 0x11da
comment = "set character from file\n"
decompiled = true

[0x1289]
last_change = 2023-12-10T07:08:41.849301Z
addr = 0x1289
func_addr = 0x123e
comment = "read 1 random byte to buf until <= 0xae\n"
decompiled = true
