[0x11b8]
last_change = 2023-12-10T06:55:32.834339Z
addr = 0x11b8
func_addr = 0x11b5
comment = "if head is null\n"
decompiled = true

[0x11e3]
last_change = 2023-12-10T07:04:11.202571Z
addr = 0x11e3
func_addr = 0x11da
comment = "if a1 is not the only node in the list\n"
decompiled = true

[0x120d]
last_change = 2023-12-10T07:03:09.307881Z
addr = 0x120d
func_addr = 0x11da
comment = "set new_node's key\n"
decompiled = true

[0x1289]
last_change = 2023-12-10T07:08:41.849301Z
addr = 0x1289
func_addr = 0x123e
comment = "read 1 random byte to buf until <= 0xae\n"
decompiled = true

[0x12c2]
last_change = 2023-12-10T07:11:04.734797Z
addr = 0x12c2
func_addr = 0x123e
comment = "quit after 175 bytes mapped into linked list\n"
decompiled = true

[0x1355]
last_change = 2023-12-10T07:11:10.058324Z
addr = 0x1355
func_addr = 0x130b
comment = "map 0x1000 bytes with rw\n"
decompiled = true

[0x139c]
last_change = 2023-12-10T07:11:34.282704Z
addr = 0x139c
func_addr = 0x130b
comment = "null a bunch of bytes\n"
decompiled = true

[0x4d68]
last_change = 2023-12-11T18:27:38.765623Z
addr = 0x4d68
comment = "Alternative name is '__init_array_end'\n"
decompiled = false
