[0x11b8]
last_change = 2023-12-10T06:55:32.834339Z
addr = 0x11b8
func_addr = 0x11b5
comment = "if head is null\n"
decompiled = true

[0x12a1]
last_change = 2023-12-10T06:57:50.728432Z
addr = 0x12a1
func_addr = 0x123e
comment = "if buf not found in list at start of v6\n"
decompiled = true
