[metadata]
name = "Elf64_Sym"
size = 0x8
last_change = 2023-12-12T19:30:05.469831Z

[members.0x0]
name = "st_name"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "st_info"
offset = 0x4
type = "unsigned char"
size = 0x1

[members.0x5]
name = "st_other"
offset = 0x5
type = "unsigned char"
size = 0x1

[members.0x6]
name = "st_shndx"
offset = 0x6
type = ""
size = 0x2
