[metadata]
name = "Elf64_Sym"
size = 0x8
last_change = 2023-12-12T19:59:23.340857Z

[members.0x0]
name = "st_name"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "st_info"
offset = 0x4
type = ""
size = 0x1
