[metadata]
name = "Elf64_Vernaux"
size = 0x8
last_change = 2023-12-11T18:40:43.161123Z

[members.0x0]
name = "vna_hash"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "vna_flags"
offset = 0x4
type = ""
size = 0x2
