[metadata]
name = "Elf64_Vernaux"
size = 0x8
last_change = 2023-12-11T18:40:38.782219Z

[members.0x0]
name = "vna_hash"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "vna_flags"
offset = 0x4
type = "unsigned short"
size = 0x2

[members.0x6]
name = "vna_other"
offset = 0x6
type = ""
size = 0x2
