[metadata]
name = "Elf64_Verneed"
size = 0x4
last_change = 2023-12-12T19:59:23.570026Z

[members.0x0]
name = "vn_version"
offset = 0x0
type = "unsigned short"
size = 0x2

[members.0x2]
name = "vn_cnt"
offset = 0x2
type = ""
size = 0x2
